CREATE TABLE `jobs` (
  `jobid` int(11) NOT NULL  DEFAULT '0',
  `status` varchar(16) NOT NULL DEFAULT 'Queued',
  `user` varchar(64) DEFAULT NULL,
  `user_group` varchar(32) DEFAULT NULL,
  `account` varchar(32) NOT NULL DEFAULT 'ZZZ',
  `jobname` varchar(128) DEFAULT NULL,
  `queue` varchar(32) DEFAULT NULL,
  `ctime` bigint(20) DEFAULT NULL,
  `qtime` bigint(20) DEFAULT NULL,
  `etime` bigint(20) DEFAULT NULL,
  `start` bigint(20) DEFAULT NULL,
  `end` bigint(20) DEFAULT NULL,
  `owner` varchar(128) DEFAULT NULL,
  `RLneednodes` varchar(64) DEFAULT NULL,
  `RLnodect` varchar(32) DEFAULT NULL,
  `RLnodes` varchar(64) DEFAULT NULL,
  `RLwalltime` varchar(32) DEFAULT NULL,
  `RLminwclimit` varchar(32) DEFAULT NULL,
  `RLflags` varchar(255) DEFAULT NULL,
  `login_node` varchar(32) DEFAULT NULL,
  `session` int(11) DEFAULT NULL,
  `exit_status` int(11) DEFAULT NULL,
  `RUcput` varchar(32) DEFAULT NULL,
  `RUmem` varchar(32) DEFAULT NULL,
  `RUvmem` varchar(32) DEFAULT NULL,
  `RUwalltime` varchar(32) DEFAULT NULL,
  `tc` int(11) DEFAULT NULL,
  `node_count` int(11) DEFAULT NULL,
  `res_tasks` bigint(20) DEFAULT NULL,
  `priority` bigint(20) DEFAULT NULL,
  `est_start` bigint(20) DEFAULT NULL,
  `moab_hold_begin` bigint(20) DEFAULT NULL,
  `moab_start` bigint(20) DEFAULT NULL,
  `moab_end` bigint(20) DEFAULT NULL,
  `moab_queue_time` bigint(20) DEFAULT '0',
  `moab_run_time` bigint(20) DEFAULT '0',
  `moab_accuracy` decimal(6,2) DEFAULT NULL,
  `moab_xfactor` decimal(10,2) DEFAULT NULL,
  `moab_wc` int(11) NOT NULL DEFAULT '0',
  `shape_x` int(11) NOT NULL  DEFAULT '0',
  `shape_y` int(11) NOT NULL  DEFAULT '0',
  `shape_z` int(11) NOT NULL  DEFAULT '0',
  `origin_x` int(11) NOT NULL  DEFAULT '0',
  `origin_y` int(11) NOT NULL  DEFAULT '0',
  `origin_z` int(11) NOT NULL DEFAULT '0',
  `resname` varchar(64) DEFAULT NULL,
  `start_type` enum('backfill','priority','reserved','admin','unknown') DEFAULT NULL,
  `preempted_by` int(11) DEFAULT NULL COMMENT 'Null if not preempted, jobid of preemptor otherwise',
  `prologue_start` bigint(20) DEFAULT NULL,
  `prologue_end` bigint(20) DEFAULT NULL,
  `epilogue_start` bigint(20) DEFAULT NULL,
  `epilogue_end` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`jobid`),
  KEY `user` (`user`),
  KEY `status` (`status`),
  KEY `tc` (`tc`)
) ENGINE=INNODB DEFAULT CHARSET=latin1
