CREATE TABLE `ovis_metrics` (
  `cTime` bigint(20) unsigned ,
  `cTime_usec` bigint(20) unsigned DEFAULT NULL,
  `DT` bigint(20) unsigned DEFAULT NULL,
  `DT_usec` bigint(20) unsigned DEFAULT NULL,
  `CompId` bigint(20) unsigned ,
  `nettopo_mesh_coord_X` bigint(20) unsigned DEFAULT NULL,
  `nettopo_mesh_coord_Y` bigint(20) unsigned DEFAULT NULL,
  `nettopo_mesh_coord_Z` bigint(20) unsigned DEFAULT NULL,
  `Xp_SAMPLE_GEMINI_LINK_BW` bigint(20) unsigned DEFAULT NULL,
  `Xn_SAMPLE_GEMINI_LINK_BW` bigint(20) unsigned DEFAULT NULL,
  `Yp_SAMPLE_GEMINI_LINK_BW` bigint(20) unsigned DEFAULT NULL,
  `Yn_SAMPLE_GEMINI_LINK_BW` bigint(20) unsigned DEFAULT NULL,
  `Zp_SAMPLE_GEMINI_LINK_BW` bigint(20) unsigned DEFAULT NULL,
  `Zn_SAMPLE_GEMINI_LINK_BW` bigint(20) unsigned DEFAULT NULL,
  `Xp_SAMPLE_GEMINI_LINK_USED_BW` bigint(20) unsigned DEFAULT NULL,
  `Xn_SAMPLE_GEMINI_LINK_USED_BW` bigint(20) unsigned DEFAULT NULL,
  `Yp_SAMPLE_GEMINI_LINK_USED_BW` bigint(20) unsigned DEFAULT NULL,
  `Yn_SAMPLE_GEMINI_LINK_USED_BW` bigint(20) unsigned DEFAULT NULL,
  `Zp_SAMPLE_GEMINI_LINK_USED_BW` bigint(20) unsigned DEFAULT NULL,
  `Zn_SAMPLE_GEMINI_LINK_USED_BW` bigint(20) unsigned DEFAULT NULL,
  `Xp_SAMPLE_GEMINI_LINK_PACKETSIZE_AVE` bigint(20) unsigned DEFAULT NULL,
  `Xn_SAMPLE_GEMINI_LINK_PACKETSIZE_AVE` bigint(20) unsigned DEFAULT NULL,
  `Yp_SAMPLE_GEMINI_LINK_PACKETSIZE_AVE` bigint(20) unsigned DEFAULT NULL,
  `Yn_SAMPLE_GEMINI_LINK_PACKETSIZE_AVE` bigint(20) unsigned DEFAULT NULL,
  `Zp_SAMPLE_GEMINI_LINK_PACKETSIZE_AVE` bigint(20) unsigned DEFAULT NULL,
  `Zn_SAMPLE_GEMINI_LINK_PACKETSIZE_AVE` bigint(20) unsigned DEFAULT NULL,
  `Xp_SAMPLE_GEMINI_LINK_INQ_STALL` bigint(20) unsigned DEFAULT NULL,
  `Xn_SAMPLE_GEMINI_LINK_INQ_STALL` bigint(20) unsigned DEFAULT NULL,
  `Yp_SAMPLE_GEMINI_LINK_INQ_STALL` bigint(20) unsigned DEFAULT NULL,
  `Yn_SAMPLE_GEMINI_LINK_INQ_STALL` bigint(20) unsigned DEFAULT NULL,
  `Zp_SAMPLE_GEMINI_LINK_INQ_STALL` bigint(20) unsigned DEFAULT NULL,
  `Zn_SAMPLE_GEMINI_LINK_INQ_STALL` bigint(20) unsigned DEFAULT NULL,
  `Xp_SAMPLE_GEMINI_LINK_CREDIT_STALL` bigint(20) unsigned DEFAULT NULL,
  `Xn_SAMPLE_GEMINI_LINK_CREDIT_STALL` bigint(20) unsigned DEFAULT NULL,
  `Yp_SAMPLE_GEMINI_LINK_CREDIT_STALL` bigint(20) unsigned DEFAULT NULL,
  `Yn_SAMPLE_GEMINI_LINK_CREDIT_STALL` bigint(20) unsigned DEFAULT NULL,
  `Zp_SAMPLE_GEMINI_LINK_CREDIT_STALL` bigint(20) unsigned DEFAULT NULL,
  `Zn_SAMPLE_GEMINI_LINK_CREDIT_STALL` bigint(20) unsigned DEFAULT NULL,
  `SAMPLE_totaloutput_optA` bigint(20) unsigned DEFAULT NULL,
  `SAMPLE_totalinput` bigint(20) unsigned DEFAULT NULL,
  `SAMPLE_fmaout` bigint(20) unsigned DEFAULT NULL,
  `SAMPLE_bteout_optA` bigint(20) unsigned DEFAULT NULL,
  `SAMPLE_bteout_optB` bigint(20) unsigned DEFAULT NULL,
  `SAMPLE_totaloutput_optB` bigint(20) unsigned DEFAULT NULL,
  `Rate_read_bytes_stats_snx11001` bigint(20) unsigned DEFAULT NULL,
  `Rate_write_bytes_stats_snx11001` bigint(20) unsigned DEFAULT NULL,
  `Rate_open_stats_snx11001` bigint(20) unsigned DEFAULT NULL,
  `Rate_close_stats_snx11001` bigint(20) unsigned DEFAULT NULL,
  `Rate_seek_stats_snx11001` bigint(20) unsigned DEFAULT NULL,
  `Rate_read_bytes_stats_snx11002` bigint(20) unsigned DEFAULT NULL,
  `Rate_write_bytes_stats_snx11002` bigint(20) unsigned DEFAULT NULL,
  `Rate_open_stats_snx11002` bigint(20) unsigned DEFAULT NULL,
  `Rate_close_stats_snx11002` bigint(20) unsigned DEFAULT NULL,
  `Rate_seek_stats_snx11002` bigint(20) unsigned DEFAULT NULL,
  `Rate_read_bytes_stats_snx11003` bigint(20) unsigned DEFAULT NULL,
  `Rate_write_bytes_stats_snx11003` bigint(20) unsigned DEFAULT NULL,
  `Rate_open_stats_snx11003` bigint(20) unsigned DEFAULT NULL,
  `Rate_close_stats_snx11003` bigint(20) unsigned DEFAULT NULL,
  `Rate_seek_stats_snx11003` bigint(20) unsigned DEFAULT NULL,
  `loadavg_latest` bigint(20) unsigned DEFAULT NULL,
  `loadavg_5min` bigint(20) unsigned DEFAULT NULL,
  `loadavg_running_processes` bigint(20) unsigned DEFAULT NULL,
  `loadavg_total_processes` bigint(20) unsigned DEFAULT NULL,
  `current_freemem` bigint(20) unsigned DEFAULT NULL,
  `Rate_SMSG_ntx` bigint(20) unsigned DEFAULT NULL,
  `Rate_SMSG_tx_bytes` bigint(20) unsigned DEFAULT NULL,
  `Rate_SMSG_nrx` bigint(20) unsigned DEFAULT NULL,
  `Rate_SMSG_rx_bytes` bigint(20) unsigned DEFAULT NULL,
  `Rate_RDMA_ntx` bigint(20) unsigned DEFAULT NULL,
  `Rate_RDMA_tx_bytes` bigint(20) unsigned DEFAULT NULL,
  `Rate_RDMA_nrx` bigint(20) unsigned DEFAULT NULL,
  `Rate_RDMA_rx_bytes` bigint(20) unsigned DEFAULT NULL,
  `Rate_ipogif0_rx_bytes` bigint(20) unsigned DEFAULT NULL,
  `Rate_ipogif0_tx_bytes` bigint(20) unsigned DEFAULT NULL,
  `Tesla_K20X_gpu_util_rate` bigint(20) NOT NULL,
  `Tesla_K20X_gpu_memory_used` bigint(20) NOT NULL,
  `Tesla_K20X_gpu_temp` bigint(20) NOT NULL,
  `Tesla_K20X_gpu_pstate` bigint(20) NOT NULL,
  `Tesla_K20X_gpu_power_limit` bigint(20) NOT NULL,
  `Tesla_K20X_gpu_power_usage` bigint(20) NOT NULL,
  `Flag` bigint(20) unsigned DEFAULT NULL,
   PRIMARY KEY (`cTime`,`CompId`),
   KEY `cTime` (`cTime`),
   KEY `CompId` (`CompId`)
) ENGINE=InnoDB;

